### ISSUE TITLE
请问你写的sql parser 是否有相关的文档或者参考内容

### ISSUE THREAD

**Issue by lostz** [wangjild/go-mysql-proxy#2]
请问你写的sql parser 是否有相关的文档或者参考内容

**Comment by wangjild** [comment]
你好，暂时还没有文档。解析规则是基于yacc的，有一份干净的文件 sql/sql_yacc.prf。 这个文件来自于mysql官方源码

**Comment by lostz** [comment]
您的代码可以直接引用,没有法律上的约束吧?

**Comment by wangjild** [comment]
规则文件来至于oracle的版权，至于我自己的，我还没想好用什么开源版本

**Comment by lostz** [comment]
好吧,yacc 太复杂了....

**Comment by wangjild** [comment]
请问
你想拿它做什么呢？

**Comment by lostz** [comment]
mysql proxy

**Comment by wangjild** [comment]
据我所知，一共就2份可以完全支持mysql语法的规则文件，其中一份就是基于yacc的，另外一份是基于antlr3的，后者在mysql-workbench的源码包中。antlr3的规则更加好理解，你可以试试

**Comment by lostz** [comment]
thx,我先学习一下.

**Comment by wangjild** [comment]
留个qq吧，保持交流~

**Comment by lostz** [comment]
已经发到你的gmail里了.
